spring:
    profiles:
        include: oauth
    h2:
        console:
            enabled: true
            path: /h2-console
        datasource:
            url: jdbc:h2:mem:testdb
            spring.datasource.url: jdbc:h2:mem:testdb
            driverClassName: org.h2.Driver
            username: sa
            password:
    jpa:
        show_sql: true
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MySQL5InnoDBDialect
                storage_engine: innodb
    datasource:
        hikari:
            jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MYSQL
    session:
#        store-type: jdbc