spring:
 activate:
  on-profile: prod
 datasource:
  driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  url: jdbc:sqlserver://marklogdbserver.database.windows.net:1433;database=marklogdb;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
  username: azuredb
  password: 'azcom@31337D'
 jpa:
  hibernate:
   ddl-auto: update