spring:
 activate:
  on-profile: dev
 datasource:
  hikari:
   jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
 jpa:
  show_sql: true
  hibernate:
   ddl-auto: create
  properties:
   hibernate:  
    dialect: com.marklog.blog.config.UnicodeSQLServer2012Dialect
 h2:
  console:
   enabled: true
   path: /h2-console