server:
 use-forward-headers: true
 servlet:
  contextPath: /api
 tomcat:
  remoteip.protocol-header: x-forwarded-proto
spring:
 profiles:
  active: dev
  include: oauth
jwt:
 accesstoken_expired: 3600000
 refreshtoken_expired: 86400000