spring:
 activate:
  on-profile: dev
 datasource:
  hikari:
   jdbc-url: jdbc:h2:mem://localhost/~/testdb;MODE=MSSQLServer
 session:
  store-type: jdbc
 jpa:
  show_sql: true
 h2:
  console:
   enabled: true
   path: /h2-console