spring:
    activate:
        on-profile: dev
    datasource:
        hikari:
            jdbc-url: jdbc:h2:file:C:/data/sample;DB_CLOSE_ON_EXIT=FALSE;MODE=MSSQLServer
    jpa:
        show_sql: true
        hibernate:
            ddl-auto: create
        properties:
            hibernate:
                dialect: com.marklog.blog.config.UnicodeSQLServer2012Dialect
    h2:
        console:
            enabled: true
            path: /h2-console
    security:
        oauth2:
            client:
                registration:
                    google:
                        redirect-uri: http://localhost:8080/api/login/oauth2/code/google
