spring:
 activate:
  on-profile: dev
 datasource:
  hikari:
   jdbc-url: jdbc:h2:~/test;MODE=MSSQLServer
 properties:
  hibernate:  
   dialect: com.marklog.blog.config.UnicodeSQLServer2012Dialect
 jpa:
  show_sql: true
  hibernate:
   ddl-auto: create
 h2:
  console:
   enabled: true
   path: /h2-console
  jdbc:
   initialize-schema: always